config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#landing_page'

  get '/login', to: 'sessions#sign_in'
  post '/login', to: 'sessions#create'
  get '/signup', to: 'users#sign_up'
  post '/signup', to: 'users#create'

  resources :posts 
  get '/chip', to: 'posts#new'
  post '/chip', to: 'posts#create'
  delete '/unchip', to: 'posts#destroy'

  get '/timeline', to: 'static_pages#timeline'

  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]

  resources :password_reset, only: [:edit, :update]

  get '/reset', to: 'password_reset#new'
  post '/reset', to: 'password_reset#create'
end

app/controllers/password_reset_controller.rb
class PasswordResetController < ApplicationController
  include PasswordResetHelper
  
  before_action :get_user, only: [:edit, :update]
  before_action :valid_user?, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new
  end

  def create
    @user = User.find_by(email: params[:reset][:email].downcase)
    if @user
      @user.create_reset_token
      @user.send_password_reset_email
      flash[:success] = "Please check your email for password reset instructions"
      redirect_to login_path
    elsif params[:reset][:email].empty?
      flash.now[:notice] = "Please fill out the email field"
      render :new
    else
      flash.now[:notice] = "No Chipper Account associated with that email"
      render :new
    end
  end

  def edit
    
  end

  def update
     if @user.update(password_reset_params)
      login @user
      flash[:success] = "Your password has been reset"
      redirect_to root_path
     elsif params[:user][:password].empty?
      @user.errors.add(:password, "can't be empty")
      render 'edit'
     else
      render 'edit'
     end
  end
end

app/helpers/password_reset_helper.rb
module PasswordResetHelper
    def password_reset_params
        params.require(:user).permit(:password)
    end

    def valid_user?
        unless @user && @user.authenticated?(:reset, params[:id])
            flash[:danger] = "Invalid password reset link"
            redirect_to root_path
        end
    end

    def check_expiration
        if @user.password_reset_expired?
            flash[:danger] = "Password reset link has expired"
            redirect to new_password_reset_path
        end
    end

    def get_user
        @user = User.find_by(email: params[:email])
    end
end

app/views/password_reset/edit.html.erb
<% provide(:button_text, 'Reset your password') %>
<div class="form-container column">
    <h1 class=" center-aligned-text form-header-text">Enter your new password</h1>
    <div class="user-admin-data-form row">
        <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
            <%= hidden_field_tag :email, @user.email %>
            <p><%= f.password_field :password %></p>
            <h5>Password must contain a lowercase, uppercase and any special character</h6>
            <div class="actions">
                <p><%= f.submit yield(:button_text) %></p>
            </div>
        <% end %>
    </div>
</div>

app/views/password_reset/new.html.erb
<% provide(:button_text, 'Reset password') %>
<div class="form-container column">
    <h1 class=" center-aligned-text form-header-text">Enter your email to get reset instructions</h1>
    <div class="form row">
        <%= form_for(:reset, url: reset_path) do |f| %>
            <p>
                <%= f.email_field :email, placeholder:'Email address' %>
            </p>
            <div class="actions">
                <p>
                    <%= f.submit yield(:button_text)%> 
                </p>
            </div>
        <% end %>
    </div>
</div>