config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#landing_page'

  get '/login', to: 'sessions#sign_in'
  post '/login', to: 'sessions#create'
  get '/signup', to: 'users#sign_up'
  post '/signup', to: 'users#create'

  resources :posts 
  get '/chip', to: 'posts#new'
  post '/chip', to: 'posts#create'
  delete '/unchip', to: 'posts#destroy'

  get '/timeline', to: 'static_pages#timeline'

  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]

  resources :password_reset, only: [:edit, :update]

  get '/reset', to: 'password_reset#new'
  post '/reset', to: 'password_reset#create'
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  has_many :posts, dependent: :destroy
  before_save :create_activation_token
  before_save :downcase_credentials
  
    VALID_EMAIL_FORMAT = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    VALID_USERNAME = /\A(?![.])(?![\s]{2})[a-zA-z_.0-9]+(?![.])\z/i
    VALID_PASSWORD_FORMAT = /((?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#_\$%\^&\*]))+/i

    validates :name, presence: true
    validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_FORMAT }
    validates :username, presence: true, length: { maximum: 15 }, uniqueness: true, format: { with: VALID_USERNAME }

    has_secure_password
    validates :password, format: { with: VALID_PASSWORD_FORMAT }

    class << self
      def digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
      end

      
    end
    
    def User.generate_token
      SecureRandom.urlsafe_base64
    end

    def remember
      self.remember_token = User.generate_token
      update_attribute(:remember_digest, User.digest(remember_token))
    end

    def is_admin?
      self.is_admin
    end

    def forget
      update_attribute(:remember_digest, nil)
    end


    def authenticated?(attribute, token)
      digest = send("#{attribute}_digest")
      return false if digest.nil?

      BCrypt::Password.new(digest).is_password?(token)
    end

    def create_reset_token
      self.reset_token = User.generate_token
      update_attribute(:reset_digest, User.digest(reset_token))
      update_attribute(:reset_sent_at, Time.zone.now)
    end

    def password_reset_expired?
      reset_sent_at < 2.hours.ago
    end

    def send_password_reset_email
      UserMailer.password_reset(self).deliver_now
    end

    def feed
      posts
    end
    

    def send_activation_email
      UserMailer.account_activation(self).deliver_now
    end
    
    def activate_user
      update_attribute(:activated, true)
      update_attribute(:activated_at, Time.zone.now)
    end

    private
      def create_activation_token
        self.activation_token = User.generate_token
        self.activation_digest = User.digest(activation_token)
      end


      def downcase_credentials
        self.email.downcase!
        self.username = self.username.downcase
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    include UsersHelper
    before_action :logged_in_user?, only: [:edit, :show, :index]
    before_action :correct_user?, only: [:edit, :show]
    before_action :is_admin?, only: [:index]

    def index
        @users = User.paginate(params[:page])
    end

    def show
        @user = User.find(params[:id])
    end
    
    def sign_up
        redirect_to current_user if logged_in?
        @user = User.new
        render 'new'
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            @user.send_activation_email
            flash[:info] = "Welcome to Chipper #{@user.name} please activate your account!" 
            login(@user)
            redirect_to user_path(@user) 
        else
            render :new
        end
    end
    
    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.authenticate(params[:user][:password])
            @user.update(user_update_params)
            flash[:success] = "Your profile updated successfully!"
            redirect_to @user
        elsif params[:user][:password].empty?
            flash[:notice] = "You need to enter your password to save changes"
            render 'edit'
        else
            flash[:notice] = "Your password is incorrect"
            render 'edit'
        end
    end


    def destroy
        @user = User.find(params[:id])    
        @user.destroy
        flash[:success] = 'Your profile was deleted successfully'
        redirect_to root_path
    end

    
end

app/helpers/users_helper.rb
module UsersHelper
    def user_params
        params.require(:user).permit(:name, :nationality, :age, :gender, :username, :password, :email)
    end

    def user_update_params
        params.require(:user).permit(:name, :nationality, :age, :gender, :username, :email)
    end

    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag( gravatar_url, alt: user.name, class: 'gravatar')
    end
end

app/views/users/_form.html.erb
<div class="form row">
  <%= form_with(model: user, local: true) do |form|%>
    <% if user.errors.any? %>
    <div class="error-explanation">

      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
  
        <ul>
        <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="field">
        <%= form.text_field :name, placeholder: "Full Name" %>
    </div>

    <div class="field">
      <%= form.text_field :email, placeholder: 'Email Address' %>
    </div>
    

    <div class="field">
      <%= form.text_field :username, placeholder: "Username" %>
      <h5>Username can contain any letter and an underscore</h6>
    </div>

    <% unless controller.action_name == 'edit' || controller.action_name == 'update' %>
      <div class="field">
        <%= form.password_field :password, placeholder: "Password" %>
        <h5>Password must contain a lowercase, uppercase and any special character</h6>
      </div>
    <% end %>
    
    <% if controller.action_name == 'edit' || controller.action_name == 'update' %>
      <div class="field">
          <%= form.number_field :age, placeholder: "Age" %>
      </div>
      
    
      <div class="field">
          <%= form.text_field :nationality, placeholder: "Nationality" %>
      </div>
    
      <div class="field">
          <%= form.text_field :gender, placeholder: "Gender" %>
      </div>

      <div class="field">
          <%= form.text_field :password, placeholder: 'Password' %>
      </div>
      
      <em>
        <%= link_to 'Delete your account?', @user, method: :delete, data: {confirm: 'Are you sure you want to delete your account? This is not reversible'}, class: 'delete-profile-button corner-form-link' %>
      </em>

    <% end  %>
    
    <div class="actions">
      <%= form.submit yield(:button_text) %>
    </div>
  <% end %>
</div>

app/views/users/_user.html.erb
<tr class="user">
    <td class="user-admin-dashboard-details"><%= user.name %></td>
    <td class="user-admin-dashboard-details"><%= user.username %></td>
    <td class="user-admin-dashboard-details"><%= user.email %></td>
    <td class="user-admin-dashboard-details"><%= user.age %></td>
    <td class="user-admin-dashboard-details"><%= user.nationality %></td>
    <td class="user-admin-dashboard-details"><%= user.activated %></td>
    <td class="user-admin-dashboard-details"><%= user.gender %></td>
    <td class="user-admin-dashboard-controls admin-user-show"><%= link_to 'Show', user %></td>
    <td class="user-admin-dashboard-controls admin-user-edit"><%= link_to 'Edit', edit_user_path(user) %></td>
    <td class="user-admin-dashboard-controls admin-user-delete"><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }%></td>
</tr>

app/views/users/edit.html.erb
<% provide(:title, 'Edit Profile') %>
<% provide(:button_text, 'Save Changes')%>
<h1 class = "admin-users-table-title center-aligned-text">Edit your profile</h1>

<div class="avatar-edit-holder row">
    <div class="column">
        <div class="avatar">
            <%= gravatar_for(@user) %>
        </div>
        <a rel="noopener" target="_blank" href="https://gravatar.com/emails">Change your avatar</a>
    </div>
</div>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
<h1 class = "admin-users-table-title center-aligned-text">Users</h1>

<table class="users-table row">
  <tr>
    <th class="users-table-header">Full name</th>
    <th class="users-table-header">Username</th>
    <th class="users-table-header">Email</th>
    <th class="users-table-header">Age</th>
    <th class="users-table-header">Nationality</th>
    <th class="users-table-header">Activation Status</th>
    <th class="users-table-header">Gender</th>
    <th class="users-table-header">View Profile</th>
    <th class="users-table-header">Edit User</th>
    <th class="users-table-header">Delete User</th>
  </tr>
  <%= render @user %>
  <%= will_paginate %>
</table>

<br>

<div class="new-admin-user-button-container row container">
  <%= link_to 'New User', signup_path, class: 'new-admin-user-button' %>
</div>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>
<% provide(:button_text, 'Sign up')%>

<div class="form-container column">
    <%= link_to image_tag('Logo.svg'), root_path, class: 'form-logo' %>
    <h1 class = "form-header-text center-aligned-text">Create a Chipper Account</h1>
    <%= render 'form', user: @user %>
    
    <p class="signup-login-section">
       Already have an account ? <%= link_to 'Login', login_path, class:'signup-login-btn' %>
    </p>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="user-profile-header">

  <div class="user-profile-info row">
    <div class="user-profile-image">
      <%= gravatar_for @user %>
    </div>
    <div class="user-name-follow-button-and-username column">
      <div class="name-username-container">
          <p>
            <strong>
              @<%= @user.username %>
            </strong>
          </p>
          <p>
            <%= @user.name %>
          </p>
      </div>
      <div class="profile-count-container row">
        <div class="count">
          <div class="count-title">
            <p>Followers</p>
          </div>
          <div class="count-data">
            <p>0</p>
          </div>
        </div>
        <div class="count">
          <div class="count-title">
            <p>Followers</p>
          </div>
          <div class="count-data">
            <p>0</p>
          </div>
        </div>
      </div>
      <div class="profile-follow-container row">
        <%unless @user == current_user%>
          <%= link_to  "Follow", edit_user_path(@user), class:'profile-follow-button'%>
        <% end %>
        <%  if logged_in? && @user == current_user %>
          <%= link_to 'Edit your profile', edit_user_path(@user), class: 'edit-user-button' %> 
        <% end %>
      </div>
    </div>
  </div>

  </div>
</div>