config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#landing_page'

  get '/login', to: 'sessions#sign_in'
  post '/login', to: 'sessions#create'
  get '/signup', to: 'users#sign_up'
  post '/signup', to: 'users#create'

  resources :posts 
  get '/chip', to: 'posts#new'
  post '/chip', to: 'posts#create'
  delete '/unchip', to: 'posts#destroy'

  get '/timeline', to: 'static_pages#timeline'

  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]

  resources :password_reset, only: [:edit, :update]

  get '/reset', to: 'password_reset#new'
  post '/reset', to: 'password_reset#create'
end

app/views/shared/_flash.html.erb
<div class="alert-container row">
    <%flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
</div>

      

app/views/shared/_logged_out_nav_actions.html.erb
<% unless logged_in? %>
    <p><%= link_to  "Login", login_path, class: 'nav-login-btn' %></p>
    <p><%= link_to  "Sign up", signup_path, class: 'nav-signup-btn' %></p>
<% end %>

app/views/shared/_modal.html.erb
<div class="column" id="modalMenu">
    <span id="close" onclick="closeModal()">
        &times
    </span>
    <ul>
        <li><%= link_to  "Home", root_path %></li>
        <% if logged_in? %>
            <li><%= link_to  "Profile", user_path(current_user) %></li>
            <li><%= link_to  "Logout", logout_path, method: :delete %></li>
        <% end %>
        <% unless logged_in? %>
            <li><%= link_to  "Login", login_path %></li>
            <li><%= link_to  "Sign up", signup_path %></li>
        <% end %>
    </ul>
</div>

app/views/shared/_nav.html.erb
  <% if controller.action_name == ' landing_page' %>  
    <nav class="navigation row">
        <%= render 'layouts/navigation' %>
    </nav>
  <% elsif controller.action_name != 'sign_up' && controller.action_name != 'sign_in' %>

    <nav class="navigation-with--bg row">
      <%= render 'layouts/navigation' %>
    </nav>    
<% end %>
    

app/views/shared/_nav_actions.html.erb
<% unless current_user.nil? %>
    <p><%= link_to  "Chip in", chip_path, class: 'chip-in' %></p>
    <% unless controller.controller_name == 'users' && controller.action_name == 'show' %>
        <p><%= link_to  "Profile", current_user, class: 'profile-btn' %></p>
    <% end %>
    <p><%= link_to  "Logout", logout_path, class: 'logout-btn', method: :delete  %> </p>
<% end %>

app/views/shared/_post.html.erb
<% if @posts.any? %>
    <% @posts.each do |post| %>
            <div class="user-detail-card row">
                    <%= gravatar_for(post.user) %>
                <div class="card-body column">
                    <div class="card-username-name row">
                        <p class="name"><%= post.user.name %></p><p class="post-username">@<%= post.user.username %></p>
                    </div>
                    <p class="post-body"><%= post.body %></p>
                    <p class="created-at">
                        <%= time_ago_in_words(post.created_at)%>
                    </p>
                </div>
            </div>
    <% end %>
<% end %>